# Generated by Django 4.0.3 on 2023-07-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_remove_appointment_status_automobilevo_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Finished', 'Finished')], default='Pending', max_length=100),
        ),
    ]
